name: tk8
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # i18n support
  flutter_translate: ^2.0.0
  intl: ^0.17.0

  # http client for api calls
  http: ^0.13.0

  # state management
  provider: ^4.3.2+2
  shared_preferences: ^2.0.0
  flutter_bloc: ^6.1.1
  rxdart: ^0.26.0

  # dependency injection
  get_it: ^6.1.1

  # data utils
  equatable: ^2.0.0

  # network images helper
  cached_network_image: ^3.0.0

  # video player support
  video_player: ^2.0.1

  # firebase
  firebase_core: ^1.0.4
  firebase_crashlytics: ^2.0.0

  # device utils
  wakelock: ^0.4.0
  share: ^2.0.1
  # TODO: Get rid of this due to no maintenance and consider flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6

  # access device media library
  image_picker: ^0.7.4
  video_thumbnail: ^0.3.3

  # secure data storage
  flutter_secure_storage: ^4.1.0

  # render svg support
  flutter_svg: ^0.21.0

  # video rating
  flutter_rating_bar: ^4.0.0

  # image editing
  image_cropper: ^1.4.0

  # in-app web browsing
  webview_flutter: ^2.0.4
  url_launcher: ^6.0.0

  # rich text / markup
  flutter_html: ^2.0.0-nullsafety.0

  # email validation
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^4.1.3
  mock_data: ^1.2.8
  fake_async: ^1.2.0
  bloc_test: ^7.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/i18n/
    - assets/svg/
    - assets/images/

  fonts:
    - family: RevxNeue
      fonts:
        - asset: assets/fonts/RevxNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/RevxNeue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RevxNeue-Bold.ttf
          weight: 700
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Book.ttf
          weight: 400
