
APP_PROJECT_DIR = "**/app"

RELEASE_NOTES = begin
  File.read("./notes.md")
rescue
  UI.message("There are no release notes provided. Using no release notes message.")
  "There are no release notes provided"
end

BUILD_INFO = {
  dev: {
    firebase_app_id: '1:239686247552:android:40d6dbae0bed36a2ddf265'
  },
  staging: {
    firebase_app_id: '1:239686247552:android:8920050b8991933bddf265'
  }
}

default_platform(:android)

platform :android do

  def increment_build_number
    increment_version_code(
      app_project_dir: APP_PROJECT_DIR,
    )
  end

  def commit_new_build_number
    version_code = get_version_code(
    app_project_dir: APP_PROJECT_DIR,
  )
    git_commit(
      path: "./app/build.gradle",
      message: "Fastlane Android: Incremented build number to #{version_code}"
    )
  end

  def do_build(flavor:)

    # build app
    build_flutter(flavor: flavor)


    # upload to firebase
    app_info = BUILD_INFO[flavor]
    apk_name = "app-#{flavor}-release.apk"
    apk_file = "../build/app/outputs/apk/#{flavor}/release/#{apk_name}"
    firebase_app_distribution(
      app: app_info[:firebase_app_id],
      firebase_cli_token: '1//09GPpBfv7OeOvCgYIARAAGAkSNwF-L9Ir5q6SSUa9asVLmlFWAYqyPLITwrTZTOXwit3h042EY24OhzQzk66FcEPm0YRbwJKY8y4',
      apk_path: apk_file,
      release_notes: RELEASE_NOTES,
      groups: 'test-group',

    )

  end

  private_lane :build_flutter do |options|
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "apk", "--flavor", "#{options[:flavor]}", "--dart-define=BUILD_TYPE=#{options[:flavor]}")
    end
  end

  desc "Upload a new Development build to AppCenter"
  lane :development do
    increment_build_number
    do_build(flavor: :dev)
    commit_new_build_number
  end

  desc "Upload a new Staging build to AppCenter"
  lane :staging do
    do_build(flavor: :staging)
  end

  desc "Submit a new build to the Play Store Internal track"
  lane :playstore do

    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    #We either need to build .apk or .aab so in the future we can remove one of both lines
    #builds the .apk archive
    sh("flutter", "build", "apk", "--flavor", "store", "--dart-define=BUILD_TYPE=store")
    #builds the .aab archive
    sh("flutter", "build", "appbundle", "--flavor", "store", "--dart-define=BUILD_TYPE=store")

    #There are some unknowns here like for example we need to get the json key and we need to know if we want to upload an .apk or .aab
    upload_to_play_store(
      package_name: 'com.njiuko.tk8',
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_apk: true,
      aab: './app/build/outputs/bundle/storeRelease/app.aab',
      json_key: 'fastlane/tk8_playstore_fastlane_key.json', #Not yet provided
      track: 'internal',
      release_status: 'draft',
    )
  end
end
